### ISSUE TITLE
Feature request: expanding/collapsing comments on mobile!

### ISSUE THREAD

**Issue by christos-christidis** [GabrielePicco/hacker-news-rich#6]
Hey this feature works great on web, but not when I'm reading on my phone. There's no collapsing there! Otherwise, great work!

**Comment by GabrielePicco** [comment]
Thanks for spotting this. The master version now also has the collapse feature in mobile view.

**Comment by GabrielePicco** [comment]
Thanks for spotting this. The master version now also has the collapse feature in mobile view.
